### ISSUE TITLE
help find your package

### ISSUE THREAD

**Issue by Scrum** [Vanilla-IceCream/rollup-plugin-posthtml-template#1]
@Shyam-Chen Hi, I am a posthtml package maintainer, I found your package because you have a posthtml package in dependencies. I think it will be easier for people to find your package if you add it to the list of plugins [here](https://github.com/posthtml/posthtml#plugins) and [here](https://github.com/posthtml/posthtml-plugins/), and of course the first thing to do in the posthtml organization itself - I can move your package to the posthtml organization for more popularity, for this it will be necessary to add me to this repository and then I will transfer it. The package itself will remain under your control.

let me know about any decision you make, i will understand if you are not interested

**Comment by Scrum** [comment]
@Shyam-Chen ping

**Comment by Shyam-Chen** [comment]
I have added you to the collaborators.
Link: https://github.com/Vanilla-IceCream/rollup-plugin-posthtml-template/invitations

**Comment by Scrum** [comment]
@Shyam-Chen the transfer was successful, accept the [invite](https://github.com/posthtml/rollup-plugin-posthtml-template/invitations) and check the rights.

Let me know if I can help you with anything else.
